xcodebuild_arguments: ["-workspace", "Tabman.xcworkspace", "-scheme", "Tabman"]
module: Tabman
clean: true
author: UI At Six
author_url: https://github.com/uias
github_url: https://github.com/uias/Tabman
# podspec: Tabman.podspec

skip_undocumented: true
abstract: Docs/tmp/sections/*.md
documentation: Docs/tmp/docs/*md

copyright: '© 2018 [UI At Six](https://github.com/uias) under [open source license](https://github.com/uias/Tabman/blob/master/LICENSE).'

swift_version: 4.2

theme: fullwidth

custom_categories:
  - name: Documentation
    children:
    - Example Projects
    - Going Custom
    - Contributing
    - Changelog
    
  - name: View Controller
    children:
    - TabmanViewController
    
  - name: Bar
    children:
    - TMBar
    - TMBarView
    - TMBarItem
    - TMBarDataSource
    - TMBarDelegate
    - TMSystemBar

  - name: Layout
    children:
    - TMBarLayout
    - TMHorizontalBarLayout
    - TMConstrainedHorizontalBarLayout

  - name: Buttons
    children:
    - TMBarButton
    - TMLabelBarButton
    - TMTabItemBarButton

  - name: Indicator
    children:
    - TMBarIndicator
    - TMLineBarIndicator
