language: objective-c

branches:
  except:
    - gh-pages

osx_image: xcode10

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="Tabman"
    - UPDATE_DOCS="true"

before_install:
- export HOMEBREW_NO_AUTO_UPDATE=1
- brew outdated carthage || brew upgrade carthage
- bundle install

script:
- .travis/build.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
# - test $TRAVIS_PULL_REQUEST == "false" &&
  # test $TRAVIS_BRANCH == "master" &&
  # test $UPDATE_DOCS == "true" &&
  # .scripts/update-gh-pages

notifications:
  email: false